apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/summerwind/actions-runner-controller/releases/download/v0.15.0/actions-runner-controller.yaml
  - https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.3/aio/deploy/recommended.yaml
